name: CI/CD TechNova

on:
  push:
    branches: [main, production, development]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true 

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          
      - name: Run Pytest with Coverage
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: pytest --cov=app --cov-report=term test_main.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true # On récupère le vrai binaire pour l'envoyer

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'

      - name: Install HF Hub
        run: pip install huggingface_hub

      - name: Upload to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          api.upload_folder(
              folder_path='.',
              repo_id='Lavin2110/projet5_OC',
              repo_type='space',
              token='${{ secrets.HF_TOKEN }}',
              ignore_patterns=['.git*', 'venv*', '__pycache__*']
          )