name: CI/CD TechNova

on:
  push:
    branches: 
      - main
      - production
      - development
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Récupère tout l'historique et toutes les branches

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.12'
          
      - name: Install dependencies
        run: |
          pwd
          pip install --upgrade pip
          pip install .
          
      - name: Run Pytest with Coverage
        # On passe les secrets ici pour que les tests puissent se connecter à la DB
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: pytest --cov=app --cov-report=term test_main.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      
      - name: Push to Hugging Face
        continue-on-error: true  
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .
          git commit -m "Export to HFS"
          git push --force https://Lavin2110:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Lavin2110/projet5_OC main
